apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    io.portainer.kubernetes.application.note: ""
  creationTimestamp: "2023-11-24T12:22:07Z"
  generation: 3
  labels:
    io.portainer.kubernetes.application.name: mscart
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: mscart
    manager: Mozilla
    operation: Update
    time: "2023-11-24T12:47:42Z"
  - apiVersion: apps/v1
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2023-12-16T00:29:44Z"
  name: mscart
  namespace: jenkins-ns
  resourceVersion: "41885289"
  uid: b71f0e39-5c29-44d0-91ff-640900d702ae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mscart
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mscart
        io.portainer.kubernetes.application.name: mscart
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker3
            weight: 1
      containers:
      - image: harbor.drobek.lan/jenkins/mscart:latest
        imagePullPolicy: IfNotPresent
        name: mscart
        resources:
          limits:
            cpu: 500m
            memory: 512M
          requests:
            cpu: 500m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-24T12:22:07Z"
    lastUpdateTime: "2023-11-24T12:22:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-24T12:22:07Z"
    lastUpdateTime: "2023-11-24T12:47:46Z"
    message: ReplicaSet "mscart-555777df4f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-24T12:22:07Z"
  labels:
    io.portainer.kubernetes.application.name: mscart
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: mscart
    manager: Mozilla
    operation: Update
    time: "2023-11-24T12:28:17Z"
  name: mscart
  namespace: jenkins-ns
spec:
  clusterIP: 10.99.124.139
  clusterIPs:
  - 10.99.124.139
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-0
    nodePort: 30100
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mscart
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
