apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    io.portainer.kubernetes.application.note: ""
  creationTimestamp: "2023-10-24T19:41:38Z"
  generation: 1
  labels:
    io.portainer.kubernetes.application.name: msfront
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: msfront
  managedFields:
  - apiVersion: apps/v1
    manager: Mozilla
    operation: Update
    time: "2023-10-24T19:41:38Z"
  - apiVersion: apps/v1
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2023-12-16T00:22:34Z"
  name: msfront
  namespace: jenkins-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: msfront
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: msfront
        io.portainer.kubernetes.application.name: msfront
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker2
            weight: 1
      containers:
      - image: harbor.drobek.lan/jenkins/msfront:latest
        imagePullPolicy: Always
        name: msfront
        resources:
          limits:
            cpu: 500m
            memory: 512M
          requests:
            cpu: 500m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-24T19:41:38Z"
    lastUpdateTime: "2023-10-24T19:41:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-24T19:41:38Z"
    lastUpdateTime: "2023-10-24T19:41:42Z"
    message: ReplicaSet "msfront-6bc8dccfdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-24T19:41:38Z"
  labels:
    io.portainer.kubernetes.application.name: msfront
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: msfront
    manager: Mozilla
    operation: Update
    time: "2023-10-24T19:41:38Z"
  name: msfront
  namespace: jenkins-ns
spec:
  clusterIP: 10.101.50.31
  clusterIPs:
  - 10.101.50.31
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-0
    nodePort: 30090
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: msfront
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
